### ISSUE TITLE
GraalVM Native Image

### ISSUE THREAD

**Issue by ryan-2048** [thingsboard/thingsboard-edge#103]
Is it possible to support compiling Native Images with GraalVM? I have encountered reflection issues. If it can be compiled into binary files, it will be a great success for low performance machines!

========================================================================================================================
GraalVM Native Image: Generating 'tb-edge-3.5.1.1EDGE-boot' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (7.3s @ 0.23GB)
 Version info: 'GraalVM 22.3.5 Java 11 EE'
 Java version info: '11.0.22+9-LTS-jvmci-22.3-b32'
 C compiler: gcc (linux, x86_64, 9.4.0)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [******]                                                                  (25.2s @ 1.11GB)
   3,547 (75.12%) of  4,722 classes reachable
   4,613 (55.13%) of  8,368 fields reachable
  17,333 (48.80%) of 35,519 methods reachable
     147 classes,     0 fields, and   475 methods registered for reflection
      59 classes,    59 fields, and    52 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                               (2.6s @ 1.70GB)

Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.PropertiesLauncher.wrapWithCustomClassLoader(PropertiesLauncher.java:368)
Warning: Reflection method java.lang.Class.forName invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
Warning: Reflection method java.lang.Class.getMethod invoked at org.springframework.boot.loader.jar.JarFileEntries.<clinit>(JarFileEntries.java:66)
Warning: Reflection method java.lang.Class.getDeclaredMethod invoked at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.PropertiesLauncher.newClassLoader(PropertiesLauncher.java:385)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at org.springframework.boot.loader.jar.Handler.getFallbackHandler(Handler.java:200)
Warning: Aborting stand-alone image build due to reflection use without configuration.
Warning: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
------------------------------------------------------------------------------------------------------------------------
                        1.0s (2.7% of total time) in 15 GCs | Peak RSS: 2.25GB | CPU load: 3.25
========================================================================================================================
Failed generating 'tb-edge-3.5.1.1EDGE-boot' after 35.5s.
Generating fallback image...
Warning: Image 'tb-edge-3.5.1.1EDGE-boot' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).

**Comment by AndriiLandiak** [comment]
I am closing this issue due to inactivity. Please feel free to reopen it if you have any more questions.

**Comment by ryan-2048** [comment]
I wanted to release a native image (instead of a. jar file) to greatly improve performance, but was unsuccessful.

**Comment by ryan-2048** [comment]
@AndriiLandiak
