### ISSUE TITLE
Issue: Error in Edge Rule Chain When Using a Rule Chain Node

### ISSUE THREAD

**Issue by OWIPEXDEV** [thingsboard/thingsboard-edge#128]
**Describe the bug**
I encountered an error in the edge rule chain when using a rule chain node inside the root rule chain.

**Error log**
```
org.thingsboard.rule.engine.api.TbNodeException: java.lang.IllegalArgumentException: Can't convert value: {"forwardMsgToDefaultRuleChain":true,"ruleChainId":"70128400-a73d-11ef-9e35-4f5b0b9e256e"}
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:45)
	at org.thingsboard.rule.engine.flow.TbRuleChainInputNode.init(TbRuleChainInputNode.java:54)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.initComponent(RuleNodeActorMessageProcessor.java:178)
	at org.thingsboard.server.actors.ruleChain.RuleNodeActorMessageProcessor.start(RuleNodeActorMessageProcessor.java:67)
	at org.thingsboard.server.actors.service.ComponentActor.initProcessor(ComponentActor.java:63)
	at org.thingsboard.server.actors.service.ComponentActor.init(ComponentActor.java:57)
	at org.thingsboard.server.actors.TbActorMailbox.tryInit(TbActorMailbox.java:68)
	at org.thingsboard.server.actors.TbActorMailbox.lambda$initActor$0(TbActorMailbox.java:61)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: Can't convert value: {"forwardMsgToDefaultRuleChain":true,"ruleChainId":"70128400-a73d-11ef-9e35-4f5b0b9e256e"}
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:157)
	at org.thingsboard.rule.engine.api.util.TbNodeUtils.convert(TbNodeUtils.java:43)
	... 13 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "forwardMsgToDefaultRuleChain" (class org.thingsboard.rule.engine.flow.TbRuleChainInputNodeConfiguration), not marked as ignorable (one known property: "ruleChainId"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.thingsboard.rule.engine.flow.TbRuleChainInputNodeConfiguration["forwardMsgToDefaultRuleChain"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2036)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
	at org.thingsboard.common.util.JacksonUtil.treeToValue(JacksonUtil.java:155)
	... 14 more

```

**Environment Details:**
ThingsBoard CE Version: v3.8.1
Edge Version: v3.6.4

* OS: Linux*
* Version 22.04 LTS*

**Screenshots**

<img width="1138" alt="Rule Node" src="https://github.com/user-attachments/assets/375e1af5-6392-412e-b32a-c7c231725d64">

<img width="939" alt="Error on start" src="https://github.com/user-attachments/assets/a2073c1b-d63d-44b3-87a2-395ce8c7752a">

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AndriiLandiak** [comment]
Hello, @OWIPEXDEV!

Thanks for bringing the issue to our attention. The **forwardMsgToDefaultRuleChain** field for the Change Originator node was added in 3.7.0. To fix this issue, please upgrade for compatibility.

We are committed to ensuring backward compatibility, but sometimes new features cause issues. The recent refactoring in the Major 3.7.0 release has impacted compatibility with Edge 3.6.3/3.6.4. I recommend upgrading Edge to 3.8.1. This will resolve this issue and bring additional improvements.

**Comment by AndriiLandiak** [comment]
Close this due to inactivity. Do not hesitate to contact us if you have any further questions. If the question is related to this topic or another one, please reopen the ticket or create a new one.
