### ISSUE TITLE
[Bug] License server 

### ISSUE THREAD

**Issue by NATSIRTIOT** [thingsboard/thingsboard-edge#2]
**Describe the bug**
When following the installation guide to install thingsboard edge (https://thingsboard.io/docs/user-guide/install/edge/deb-installation/?edgeInstallCloud=ce
) on raspberry pi4, I got the error "ERROR o.t.license.client.TbLicenseClient - License Error: CONNECTION_ERROR(400) - Failed to connect to ThingsBoard License Server! "
when I tried to restart the thingsboard edge service.

Below you can find the stack trace and the configuration file (tb-edge.conf).
How can I solve this?

**Your Server Environment**
* demo.thingsboard.io

**Your Client Environment**
**Desktop :**
* Raspberry Pi 4B
* OS: Raspbian
** Stack trace **
```
2022-02-22 14:15:41,149 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.5]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.6]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.3]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.4]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.1]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.2]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.0]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.9]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.7]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.8]: 0 devices
2022-02-22 14:15:41,152 [main] INFO  o.t.s.s.t.TbCoreTransportApiService - Received application ready event. Starting polling for events.
2022-02-22 14:15:41,154 [scheduler-service-22-thread-1] INFO  o.t.s.s.s.DefaultSchedulerService - Scheduler service initialized.
2022-02-22 14:15:41,155 [main] INFO  o.t.s.a.service.DefaultActorService - Received application ready event. Sending application init message to actor system
2022-02-22 14:15:41,157 [main] INFO  o.t.s.s.q.p.AbstractConsumerService - Subscribing to notifications: tb_rule_engine.notifications.raspberrypi
2022-02-22 14:15:41,164 [main] INFO  o.t.s.s.q.p.AbstractConsumerService - Subscribing to notifications: tb_core.notifications.raspberrypi
2022-02-22 14:15:41,299 [default-integration-refresh-1-1] INFO  o.t.s.s.i.DefaultPlatformIntegrationService - 0 Integrations refreshed
2022-02-22 14:15:42,109 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated addedPartitions [TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.sq.9, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.sq.8, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.sq.7, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.sq.2, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.sq.1, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.sq.0, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.sq.6, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.sq.5, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.sq.4, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.sq.3, myPartition=true)]
2022-02-22 14:15:42,110 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated removedPartitions []
2022-02-22 14:15:42,113 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.sq.9, myPartition=true)
2022-02-22 14:15:42,117 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.sq.8, myPartition=true)
2022-02-22 14:15:42,118 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.sq.7, myPartition=true)
2022-02-22 14:15:42,119 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.sq.2, myPartition=true)
2022-02-22 14:15:42,120 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.sq.1, myPartition=true)
2022-02-22 14:15:42,121 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.sq.0, myPartition=true)
2022-02-22 14:15:42,122 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.sq.6, myPartition=true)
2022-02-22 14:15:42,123 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.sq.5, myPartition=true)
2022-02-22 14:15:42,124 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.sq.4, myPartition=true)
2022-02-22 14:15:42,125 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [SequentialByOriginator] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.sq, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.sq.3, myPartition=true)
2022-02-22 14:15:42,147 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated addedPartitions [TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.main.8, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.main.9, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.main.6, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.main.7, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.main.4, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.main.5, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.main.2, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.main.3, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.main.0, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.main.1, myPartition=true)]
2022-02-22 14:15:42,148 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated removedPartitions []
2022-02-22 14:15:42,148 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.main.8, myPartition=true)
2022-02-22 14:15:42,149 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.main.9, myPartition=true)
2022-02-22 14:15:42,150 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.main.6, myPartition=true)
2022-02-22 14:15:42,151 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.main.7, myPartition=true)
2022-02-22 14:15:42,152 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.main.4, myPartition=true)
2022-02-22 14:15:42,153 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.main.5, myPartition=true)
2022-02-22 14:15:42,154 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.main.2, myPartition=true)
2022-02-22 14:15:42,155 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.main.3, myPartition=true)
2022-02-22 14:15:42,156 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.main.0, myPartition=true)
2022-02-22 14:15:42,157 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [Main] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.main, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.main.1, myPartition=true)
2022-02-22 14:15:42,158 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated addedPartitions [TopicP2022-02-22 14:15:41,149 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.5]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.6]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.3]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.4]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.1]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.2]: 0 devices
2022-02-22 14:15:41,150 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.0]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.9]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.7]: 0 devices
2022-02-22 14:15:41,151 [device-state-scheduled-19-thread-1] INFO  o.t.s.s.s.DefaultDeviceStateService - [tb_core.8]: 0 devices
2022-02-22 14:15:41,152 [main] INFO  o.t.s.s.t.TbCoreTransportApiService - Received application ready event. Starting polling for events.
2022-02-22 14:15:41,154 [scheduler-service-22-thread-1] INFO  o.t.s.s.s.DefaultSchartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.hp.9, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.hp.7, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.hp.8, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.hp.5, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.hp.6, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.hp.3, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.hp.4, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.hp.1, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.hp.2, myPartition=true), TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.hp.0, myPartition=true)]
2022-02-22 14:15:42,159 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - calculated removedPartitions []
2022-02-22 14:15:42,159 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[9], fullTopicName=tb_rule_engine.hp.9, myPartition=true)
2022-02-22 14:15:42,160 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[7], fullTopicName=tb_rule_engine.hp.7, myPartition=true)
2022-02-22 14:15:42,161 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[8], fullTopicName=tb_rule_engine.hp.8, myPartition=true)
2022-02-22 14:15:42,162 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[5], fullTopicName=tb_rule_engine.hp.5, myPartition=true)
2022-02-22 14:15:42,163 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[6], fullTopicName=tb_rule_engine.hp.6, myPartition=true)
2022-02-22 14:15:42,164 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[3], fullTopicName=tb_rule_engine.hp.3, myPartition=true)
2022-02-22 14:15:42,164 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[4], fullTopicName=tb_rule_engine.hp.4, myPartition=true)
2022-02-22 14:15:42,165 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[1], fullTopicName=tb_rule_engine.hp.1, myPartition=true)
2022-02-22 14:15:42,166 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[2], fullTopicName=tb_rule_engine.hp.2, myPartition=true)
2022-02-22 14:15:42,167 [tb-rule-engine-consumer-repartition-43-thread-1] INFO  o.t.s.s.q.DefaultTbRuleEngineConsumerService - [HighPriority] Adding consumer for topic: TopicPartitionInfo(topic=tb_rule_engine.hp, tenantId=Optional.empty, partition=Optional[0], fullTopicName=tb_rule_engine.hp.0, myPartition=true)
2022-02-22 14:15:43,470 [grpc-default-executor-1] INFO  o.t.edge.rpc.EdgeGrpcClient - [be5d25a5-5fcf-7bb9-a0e1-5193f79aacb6] Configuration received: edgeIdMSB: -5933526591518666260
edgeIdLSB: -5828491829665300205
tenantIdMSB: -3549256792285703700
tenantIdLSB: -5828491829665300205
customerIdMSB: 1405474927960789426
customerIdLSB: -9187201950435737472
name: "My New Edge"
type: "default"
routingKey: "myroutingkeyy"
secret: "my secret"
edgeLicenseKey: "{\"description\":\"\"}"
cloudEndpoint: "CE"

2022-02-22 14:15:43,848 [grpc-default-executor-1] INFO  o.t.license.client.TbLicenseClient - Initializing ThingsBoard License Client, Release Date [2022-01-28]
2022-02-22 14:15:44,205 [grpc-default-executor-1] ERROR o.t.license.client.TbLicenseClient - License Error: CONNECTION_ERROR(400) - Failed to connect to ThingsBoard License Server!
2022-02-22 14:15:44,206 [grpc-default-executor-1] ERROR o.t.license.client.TbLicenseClient - Failed to initialize ThingsBoard License Client!
2022-02-22 14:15:44,216 [grpc-default-executor-1] ERROR o.t.s.d.s.BasicSubscriptionService - Failed to init license client
org.thingsboard.license.shared.exception.LicenseException: Failed to connect to ThingsBoard License Server!
	at org.thingsboard.license.client.TbLicenseClient.toLicenseException(TbLicenseClient.java:405)
	at org.thingsboard.license.client.TbLicenseClient.activateInstance(TbLicenseClient.java:331)
	at org.thingsboard.license.client.TbLicenseClient.readInstanceDataOrActivate(TbLicenseClient.java:316)
	at org.thingsboard.license.client.TbLicenseClient.init(TbLicenseClient.java:171)
	at org.thingsboard.server.dao.subscription.BasicSubscriptionService.init(BasicSubscriptionService.java:101)
	at org.thingsboard.server.service.cloud.CloudManagerService.onEdgeUpdate(CloudManagerService.java:559)
	at org.thingsboard.edge.rpc.EdgeGrpcClient$1.onNext(EdgeGrpcClient.java:136)
	at org.thingsboard.edge.rpc.EdgeGrpcClient$1.onNext(EdgeGrpcClient.java:129)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:466)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onMessage(DelayedClientCall.java:447)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:661)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:646)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on POST request for "/CE/api/license/activateInstance": null; nested exception is org.apache.http.client.ClientProtocolException
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:746)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:693)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:456)
	at org.thingsboard.license.client.TbLicenseClient.activateInstance(TbLicenseClient.java:327)
	... 15 common frames omitted
Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:87)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:737)
	... 18 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 24 common frames omitted
2022-02-22 14:15:44,223 [Shutdown Thread] INFO  o.t.s.d.s.BasicSubscriptionService - Terminating application due to critical License Error CONNECTION_ERROR(400), exit code [-1]...
2022-02-22 14:15:44,269 [SpringContextShutdownHook] INFO  o.s.i.endpoint.EventDrivenConsumer - Removing {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2022-02-22 14:15:44,269 [SpringContextShutdownHook] INFO  o.s.i.c.PublishSubscribeChannel - Channel 'application.errorChannel' has 0 subscriber(s).
2022-02-22 14:15:44,270 [SpringContextShutdownHook] INFO  o.s.i.endpoint.EventDrivenConsumer - stopped bean '_org.springframework.integration.errorLogger'
2022-02-22 14:15:44,297 [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2022-02-22 14:15:44,298 [SpringContextShutdownHook] INFO  o.s.s.c.ThreadPoolTaskScheduler - Shutting down ExecutorService 'taskScheduler'
2022-02-22 14:15:44,353 [SpringContextShutdownHook] INFO  o.t.s.t.coap.CoapTransportService - CoAP transport stopped!
2022-02-22 14:15:44,355 [SpringContextShutdownHook] INFO  o.t.s.t.mqtt.MqttTransportService - Stopping MQTT transport!
2022-02-22 14:15:44,361 [SpringContextShutdownHook] INFO  o.t.s.t.mqtt.MqttTransportService - MQTT transport stopped!
2022-02-22 14:15:44,366 [tb-core-notifications-consumer-48-thread-1] INFO  o.t.s.s.q.p.AbstractConsumerService - TB Notifications Consumer stopped.
2022-02-22 14:15:44,367 [tb-core-usage-stats-consumer-49-thread-1] INFO  o.t.s.s.q.DefaultTbCoreConsumerService - TB Usage Stats Consumer stopped.
2022-02-22 14:15:44,368 [tb-core-consumer-47-thread-1] INFO  o.t.s.s.q.DefaultTbCoreConsumerService - TB Core Consumer stopped.
2022-02-22 14:15:44,368 [tb-core-firmware-notifications-consumer-50-thread-1] INFO  o.t.s.s.q.DefaultTbCoreConsumerService - TB Ota Package States Consumer stopped.
```

**Screenshots**
This is my config file
```
export JAVA_OPTS="$JAVA_OPTS -Dplatform=deb -Dinstall.data_dir=/usr/share/tb-edge/data"
export JAVA_OPTS="$JAVA_OPTS -Xlog:gc*,heap*,age*,safepoint=debug:file=/var/log/tb-edge/gc.log:time,uptime,level,tags:filecount=10,filesize=10M"
export JAVA_OPTS="$JAVA_OPTS -XX:+IgnoreUnrecognizedVMOptions -XX:+HeapDumpOnOutOfMemoryError"
export JAVA_OPTS="$JAVA_OPTS -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+ResizeTLAB -XX:+PerfDisableSharedMem -XX:+UseCondCardMark"
export JAVA_OPTS="$JAVA_OPTS -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:MaxTenuringThreshold=10"
export LOG_FILENAME=tb-edge.out
export LOADER_PATH=/usr/share/tb-edge/conf,/usr/share/tb-edge/extensions
export SQL_DATA_FOLDER=/usr/share/tb-edge/data/sql

# UNCOMMENT NEXT LINES AND PUT YOUR CLOUD CONNECTION SETTINGS:
export CLOUD_ROUTING_KEY=myroutingkeyy
export CLOUD_ROUTING_SECRET=mysecret

# UNCOMMENT NEXT LINES IF EDGE CONNECTS TO PE 'THINGSBOARD.CLOUD' SERVER:
# export CLOUD_RPC_HOST=thingsboard.cloud
# export CLOUD_RPC_SSL_ENABLED=true

# UNCOMMENT NEXT LINES IF EDGE CONNECTS TO CE 'DEMO.THINGSBOARD.IO' SERVER:
export CLOUD_RPC_HOST=demo.thingsboard.io

# UNCOMMENT NEXT LINES IF YOU CHANGED DEFAULT CLOUD RPC HOST/PORT SETTINGS:
#export CLOUD_RPC_HOST=localhost
#export CLOUD_RPC_PORT=7070

# UNCOMMENT NEXT LINES IF YOU ARE RUNNING EDGE ON THE SAME MACHINE WHERE THINGSBOARD SERVER IS RUNNING:
# export HTTP_BIND_PORT=18080
# export MQTT_BIND_PORT=11883
# export COAP_BIND_PORT=15683

# UNCOMMENT NEXT LINES IF YOU HAVE CHANGED DEFAULT POSTGRESQL DATASOURCE SETTINGS:
export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/tb_edge
export SPRING_DATASOURCE_USERNAME=myusername
export SPRING_DATASOURCE_PASSWORD=mypw
```

**Comment by volodymyr-babak** [comment]
@NATSIRTIOT 
most probably cloud endpoint in the edge configuration section is not set correctly.
![image](https://user-images.githubusercontent.com/3466101/162170884-5911fd90-d7fa-4c5b-82b5-a4712b1f875b.png)
it should domain name or ID address of the TB cloud, and not **CE**:
![image](https://user-images.githubusercontent.com/3466101/162171087-c0c47249-dc65-4967-86ef-8be07693e7b1.png)

**Comment by volodymyr-babak** [comment]
closing due to inactivity.
