### ISSUE TITLE
[Bug] Edge sync failed if to the edge was assigned dashboard which size is bigger than 4MB

### ISSUE THREAD

**Issue by volodymyr-babak** [thingsboard/thingsboard-edge#41]
**Describe the bug**
 Edge sync failed if to the edge was assigned dashboard which size is bigger than 4MB

**Your Server Environment**

* demo.thingsboard.io
* cloud.thingsboard.io
* own setup
  * cloud or local infrastructure or docker deployment
  * ThingsBoard Version
  * OS Name and Version

**Your Client Environment**

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**
* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Your Device**

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**
1. Create dashboard and use 'heavy' background image
2. Assign this dashboard to edge

**Expected behavior**
Dashboard is provisioned to the edge successfully. 
Or at least warning message displayed and dashboard cannot be assigned to the edge because of it's size. 

**Screenshots**

**Additional context**

**Comment by AndreMaz** [comment]
@volodymyr-babak I'm on tb-edge PE v3.5.1.1 (clean install) and when I click on `Sync Edge`  I see the following errors:

TB-Cloud
> 2023-08-04 16:01:30,097 [grpc-default-executor-821] ERROR o.t.s.s.edge.rpc.EdgeGrpcSession - [] Stream was terminated due to error:
io.grpc.StatusRuntimeException: CANCELLED: client cancelled
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:291)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:362)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:350)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:913)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-08-04 16:01:30,097 [grpc-default-executor-821] INFO  o.t.s.s.edge.rpc.EdgeGrpcService - [] edge disconnected!

> TB-Edge

2023-08-04 16:24:23,292 [grpc-default-executor-3] WARN  o.t.edge.rpc.EdgeGrpcClient - [] Stream was terminated due to error:
io.grpc.StatusRuntimeException: INTERNAL: RST_STREAM closed stream. HTTP/2 error code: PROTOCOL_ERROR
    at io.grpc.Status.asRuntimeException(Status.java:535)
    at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
    at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:463)
    at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:427)
    at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:460)
    at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
    at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
    at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
    
    
    Shouldn't this PR prevent this kind of issues?

**Comment by volodymyr-babak** [comment]
Hello @AndreMaz,

Yes, the behavior should be as you've described - it should log a warning and skip the particular message. 
Could you please provide the version of your cloud (server) - is it also 3.5.1? 
I'm going to investigate this issue further once you confirm that it's 3.5.1 as well on the cloud.

**Comment by AndreMaz** [comment]
Hi @volodymyr-babak. Yep, TB-Cloud is running on v3.5.1 PE

**Comment by AndreMaz** [comment]
Hi @AndriiLandiak thank you for quick response.

Here goes some more info
License status:
![image](https://github.com/thingsboard/thingsboard-edge/assets/9802754/87d4791a-d623-434b-9c34-1057eea4cf67)

Edge status @ TB-Cloud
![image](https://github.com/thingsboard/thingsboard-edge/assets/9802754/ec804b19-0e0e-4494-aca4-bec2e6abd453)

In Downlink tab I see that everything is marked as Deployed
**Side Node** Would be good to be able to sort the entries by the `Event action`, `Status`, `Type` and not only by `Event time` as currently happens.
![image](https://github.com/thingsboard/thingsboard-edge/assets/9802754/1110bda6-475c-4869-a51f-229ab8dd0cf0)

TB-Cloud DB with the estimated table size
![image](https://github.com/thingsboard/thingsboard-edge/assets/9802754/23729d6a-85d9-4f3a-9e08-117397e12a5c)

I've set the CLOUD_RPC_MAX_INBOUND_MESSAGE_SIZE and EDGES_RPC_MAX_INBOUND_MESSAGE_SIZE to 20971520 (ie, 20 MB) but the problem persists. 

My question is: the logic of this PR only applies to the Dashboard sync process? What about the remaining elements that flow through the gRPC link?

Also: is there anything that I can do to better see the error logs? The error that TB throws is not really useful. For example, it would be good to see the type of the element (and it's size) that TB tried to sync and caused the error

**Comment by volodymyr-babak** [comment]
@AndreMaz

From your description, it seems the issue might not be related to the size of the object but to another factor. Could you please follow these steps to help us diagnose the problem?

- On the Edge side, update the **logback.xml** file and insert the following line:

`<logger name="org.thingsboard.server.service.cloud" level="TRACE" />`

- On the Cloud side, update the **logback.xml** file and insert the following line:

`<logger name="org.thingsboard.server.service.edge" level="TRACE" />`

-  Make sure that you start seeing a lot of **TRACE** logs on both services.
-  Press the sync button.

After completing these steps, kindly attach the logs from both the edge and cloud containers. Thank you.

![2023-08-08_10-45](https://github.com/thingsboard/thingsboard-edge/assets/3466101/8cc80f2b-61cb-457e-bc49-f7cd039378b9)

**Comment by AndreMaz** [comment]
Hi @volodymyr-babak you can close the issue as it was caused by our infrastructure, [kong](https://konghq.com/) to be precise. It was closing gRPC connection after a minute or so. 

Thank you for the **logback.xml** trick, it helped me to conclude that everything was fine @ TB and led me to simplify our infrastructure, which allowed me to find out the source of the problem

Thank you again for the quick response. Really appreciate it

**Comment by volodymyr-babak** [comment]
@AndreMaz 

Thank you for your feedback. Please feel free to reopen this ticket if necessary, and don't hesitate to create a new one if you encounter any other issues.
